shallow_clone: true
# version format
version: 1.0.{build}
# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true
build:
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: sigma.scm.azurewebsites.net:443
  website: sigma
  username: $sigma
  password:
    secure: IhaZvK00JIzvrUW+ljpzeOMh5AfnLiXWc6LsT4IwMmHKS5B8hggnq+WeWZcMBgEo++2Pa+texX1Q+ytPZhoSIQ==

before_build:
  nuget restore

notifications:
  - provider: Slack
    auth_token:
      secure: xoxp-33771451379-33820609287-55826048132-4f117727bc
    channel: '#sigma-dev'
    on_build_success: false
    on_build_failure: false