shallow_clone: true
# version format
version: 1.0.{build}
# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

cache:
  - Sigma\Sigma.Website\bower_components -> Sigma\Sigma.Website\bower.json
  - Sigma\Sigma.Website\node_modules -> Sigma\Sigma.Website\package.json

install:
  - npm install -g grunt-cli  1> nul

before_build:
  - ps: .\CreateBuildTxt.ps1
  - cmd: |
          cd Sigma          
          nuget restore
          cd Sigma.Website
          npm install
          grunt
          cd ..
          cd ..
  
build:
  publish_wap: true
  project: Sigma\Sigma.sln

#Deployment configuration
deploy:
- provider: FTP
  host: waws-prod-bn1-005.ftp.azurewebsites.windows.net/site/wwwroot
  protocol: ftp
  username: sigma\$sigma
  password:
    secure: aYsx7+mSFJEgNnKbcYXl6FI72lRKggHNC8dLwJxvQE9644nQy7HJhqabFoB3EsElh+/V8pggABq+Isi3f5vYSA==
  on:
    branch: master

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#sigma-dev'
    on_build_success: true
    on_build_failure: true