version: 1.0.{build}
build:
  verbosity: minimal
  
notifications:
  - provider: Slack
    auth_token:
      secure: xoxp-33771451379-33820609287-45436685506-8dc066032d
    channel: '#larnia-dev'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true